name: new_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2 # For sending requests
  signature: ^5.0.1
  speech_to_text: 6.6.2 # Use a stable, older version
  # speech_to_text_platform_interface: 2.1.0 # Use a compatible version
  avatar_glow: ^3.0.1
  clipboard: ^0.1.3
  path_provider: ^2.0.11
  pdf: ^3.11.1
  permission_handler: ^11.1.0
  shared_preferences: ^2.0.18
  image: ^4.0.15
  provider: ^6.1.2
  # flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
